Us 6 (script de création des tables
Austreelis/Dev-Web-2022 pull request #41
Opened 2022-04-14 14:29 UTC by simonNolf

création de la db

2022-04-16 08:18 UTC, severinRobert commented
Les `COLLATE=utf8mb4_0900_ai_ci` pose problème chez moi, en les remplaçant par `COLLATE=utf8mb4_general_ci` ça règle le problème, normalement ça devrait fonctionner sur tous les systèmes.

2022-04-16 09:09 UTC, simonNolf commented
> Les `COLLATE=utf8mb4_0900_ai_ci` pose problème chez moi, en les remplaçant par `COLLATE=utf8mb4_general_ci` ça règle le problème, normalement ça devrait fonctionner sur tous les systèmes.

pas de prblème

2022-04-16 23:56 UTC, Austreelis requested changes

2022-04-16 23:56 UTC, Austreelis commented on server/migration/script0.1.0.sql
> +CREATE DATABASE IF NOT EXISTS `projet` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
I know we haven't decided on a project name yet, but it would go a long way.

2022-04-16 23:56 UTC, Austreelis commented on server/migration/script0.1.0.sql
> +  `objet` varchar(50) NOT NULL,
what is this column supposed to represent ? (Do we know yet ? If not, we should wait for the inventory's items structure to be well-defined before adding it to the database schema).

2022-04-16 23:56 UTC, Austreelis commented on server/migration/script0.1.0.sql
> +CREATE DATABASE IF NOT EXISTS `projet` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
Why are the `CHARACTER SET` and `COLLATE` instructions commented out ? All our table charsets and collates are the same anyway, we could avoid specifying them every time.

2022-04-16 23:56 UTC, Austreelis commented on server/migration/script0.1.0.sql
> +  `id_scénario` mediumint DEFAULT NULL,
What is this column representing ? An user may be related to a scenario, but that's a 1 User to many scenarios, not 1 to 1. A user may create many scenarios.

Unless it doesn't represent scenario authorship ?

2022-04-16 23:56 UTC, Austreelis commented on server/migration/script0.1.0.sql
> +-- HeidiSQL Version:             11.3.0.6295
All these comments aren't particularly useful and won't be true anymore once we will deploy the actual DB

2022-04-16 23:56 UTC, Austreelis commented on server/migration/script0.1.0.sql
> +CREATE TABLE IF NOT EXISTS `scenario` (
Why not add the column containing the scenario's JSON ?

2022-04-16 23:56 UTC, Austreelis commented on server/migration/script0.1.0.sql
> +  CONSTRAINT `fk__scenario` FOREIGN KEY (`id_scenario`) REFERENCES `scenario` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
these double-underscore kinda creep me out and it is the only place they have been used, I get it's nit picking but to me it just looks like the result of an unstable name generation from the tool that generated this script.

2022-04-17 09:02 UTC, simonNolf commented on server/migration/script0.1.0.sql
> +CREATE TABLE IF NOT EXISTS `scenario` (
i didn't find how to make the column be able to take JSON type

2022-04-23 14:53 UTC, Austreelis approved these changes

2022-04-23 14:54 UTC, merged