Unique identity
Austreelis/Dev-Web-2022 pull request #42
Opened 2022-04-16 20:20 UTC by Austreelis

Implements #38 & #39

It would be ideal if someone proof-read `doc/socket-protocol.md`

2022-04-16 20:21 UTC, Austreelis commented
@simonNolf @severinRobert @saskia-libotte Can one of you assign itself as reviewer ? :)

2022-04-18 14:18 UTC, simonNolf approved these changes

2022-04-18 14:18 UTC, simonNolf commented on common/types.ts
> +export type LowerAlpha = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i"
can we delete this?

2022-04-18 14:19 UTC, simonNolf requested changes

2022-04-18 14:19 UTC, simonNolf commented on common/types.ts
> +export type LowerAlpha = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i"
can we delete this?

2022-04-23 14:06 UTC, merged